const absoluteOrder = [
  "MENUJU LOKASI",
  "TIBA DI LOKASI",
  "GELAR PERALATAN & BRIEFING",
  "SIAP DIMULAI",
  "PEKERJAAN DILAKSANAKAN",
  "PEKERJAAN SELESAI",
  "PEKERJAAN DIHENTIKAN"
];
console.log(absoluteOrder.indexOf("GELAR PERALATAN & BRIEFING"));
